### ISSUE TITLE
Handshake Error since schedule maintenance on Jan 07

### ISSUE THREAD

**Issue by somguyth** [jnidzwetzki/bitfinex-v2-wss-api-java#100]
Ever since the scheduled maintenance I've been getting this. However, I've confirmed that the websocket endpoint being used, "wss://api.bitfinex.com/ws/2", is still valid, by checking on https://www.websocket.org/echo.html, so there's some other issue at play.

Caused by: java.lang.RuntimeException: com.github.jnidzwetzki.bitfinex.v2.entity.APIException: javax.websocket.DeploymentException: Handshake error.
	... 6 more
Caused by: com.github.jnidzwetzki.bitfinex.v2.entity.APIException: javax.websocket.DeploymentException: Handshake error.
	at com.github.jnidzwetzki.bitfinex.v2.BitfinexApiBroker.connect(BitfinexApiBroker.java:320)
	... 6 more
Caused by: javax.websocket.DeploymentException: Handshake error.
	at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:679)
	at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:717)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:871)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:516)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:378)
	at com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.connect(WebsocketClientEndpoint.java:87)
	at com.github.jnidzwetzki.bitfinex.v2.BitfinexApiBroker.connect(BitfinexApiBroker.java:311)
	... 8 more
Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 520.
	at org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:320)
	at org.glassfish.tyrus.container.jdk.client.ClientFilter.processRead(ClientFilter.java:190)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:134)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:136)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.handleRead(SslFilter.java:406)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.processRead(SslFilter.java:368)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:134)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:136)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:299)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:283)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by somguyth** [comment]
> Ever since the scheduled maintenance I've been getting this. However, I've confirmed that the websocket endpoint being used, "wss://api.bitfinex.com/ws/2", is still valid, by checking on https://www.websocket.org/echo.html, so there's some other issue at play.
> 
> Caused by: java.lang.RuntimeException: com.github.jnidzwetzki.bitfinex.v2.entity.APIException: javax.websocket.DeploymentException: Handshake error.
> ... 6 more
> Caused by: com.github.jnidzwetzki.bitfinex.v2.entity.APIException: javax.websocket.DeploymentException: Handshake error.
> at com.github.jnidzwetzki.bitfinex.v2.BitfinexApiBroker.connect(BitfinexApiBroker.java:320)
> ... 6 more
> Caused by: javax.websocket.DeploymentException: Handshake error.
> at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:679)
> at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:717)
> at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
> at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:871)
> at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
> at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:516)
> at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:378)
> at com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.connect(WebsocketClientEndpoint.java:87)
> at com.github.jnidzwetzki.bitfinex.v2.BitfinexApiBroker.connect(BitfinexApiBroker.java:311)
> ... 8 more
> Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 520.
> at org.glassfish.tyrus.client.TyrusClientEngine.processResponse(TyrusClientEngine.java:320)
> at org.glassfish.tyrus.container.jdk.client.ClientFilter.processRead(ClientFilter.java:190)
> at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:134)
> at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:136)
> at org.glassfish.tyrus.container.jdk.client.SslFilter.handleRead(SslFilter.java:406)
> at org.glassfish.tyrus.container.jdk.client.SslFilter.processRead(SslFilter.java:368)
> at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:134)
> at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:136)
> at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:299)
> at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:283)
> at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
> at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
> at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.base/java.lang.Thread.run(Thread.java:844)
