### ISSUE TITLE
ClientGroupId in BitfinexNewOrder should be Long instead of Integer

### ISSUE THREAD

**Issue by nschmid** [jnidzwetzki/bitfinex-v2-wss-api-java#104]
I'm getting following number format exception (input can't be parsed to Integer):

`2019-02-07 14:59:26.546 ERROR 16221 --- [us-jdk-client-2] c.g.j.b.v2.SimpleBitfinexApiBroker       : OnError called java.lang.NumberFormatException: For input string: "1569445422239"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.github.jnidzwetzki.bitfinex.v2.callback.channel.account.info.OrderHandler.jsonToBitfinexSubmittedOrder(OrderHandler.java:95)
	at com.github.jnidzwetzki.bitfinex.v2.callback.channel.account.info.OrderHandler.handleChannelData(OrderHandler.java:74)
	at com.github.jnidzwetzki.bitfinex.v2.callback.channel.AccountInfoHandler.handleChannelData(AccountInfoHandler.java:108)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.handleChannelCallback(SimpleBitfinexApiBroker.java:591)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.websocketCallback(SimpleBitfinexApiBroker.java:524)
	at com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.onMessage(WebsocketClientEndpoint.java:117)
`

I guess, the clientGroupId in BitfinexNewOrder should be a Long instead.

**Comment by mironbalcerzak** [comment]
Something must have changed in bitfinex backend.
I clearly remember that clientGroupId was meant to be of type java.lang.Integer.

I see that docs no longer specify int32, int64 - but just int - which must mean java.lang.Long type.. lib must be review then.

-- mb

**Comment by jnidzwetzki** [comment]
Yes, unfortunately Bitfinex often changes something at the API without announcing it. 

@nschmid Thanks for the pull request.
