### ISSUE TITLE
Getting Connection Closed In WebSocket Orderbook API

### ISSUE THREAD

**Issue by achavan51** [jnidzwetzki/bitfinex-v2-wss-api-java#15]
Hi,
While running the WebSocket order book API in the multithreaded environment I am getting the Handshake exception...

here is error message:>

javax.websocket.DeploymentException: Handshake error.
com.draglet.exception.OrderbookException: javax.websocket.DeploymentException: Handshake error.
	at com.draglet.service.communicator.BitfinexCommunicator.getOrderBook(BitfinexCommunicator.java:198) ~[classes/:?]
	at com.draglet.service.communicator.BitfinexCommunicator.getOrderBook(BitfinexCommunicator.java:51) ~[classes/:?]
	at com.draglet.OrderFetcher.doWork(OrderFetcher.java:181) ~[classes/:?]
	at com.draglet.worker.DatabaseOrderWorker.run(DatabaseOrderWorker.java:78) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: Handshake error.
	at com.draglet.service.websocket.WebsocketClientEndpoints.<init>(WebsocketClientEndpoints.java:35) ~[classes/:?]
	at com.draglet.service.websocket.WeSocketHandler.websocket(WeSocketHandler.java:24) ~[classes/:?]
	at com.draglet.service.communicator.BitfinexCommunicator.getOrderBook(BitfinexCommunicator.java:194) ~[classes/:?]
	... 8 more
Caused by: javax.websocket.DeploymentException: Handshake error.
	at org.glassfish.tyrus.client.ClientManager$1$1.run(ClientManager.java:552) ~[tyrus-standalone-client-1.7.jar:?]
	at org.glassfish.tyrus.client.ClientManager$1.run(ClientManager.java:582) ~[tyrus-standalone-client-1.7.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
	at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:734) ~[tyrus-standalone-client-1.7.jar:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_161]
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:431) ~[tyrus-standalone-client-1.7.jar:?]
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:321) ~[tyrus-standalone-client-1.7.jar:?]
	at com.draglet.service.websocket.WebsocketClientEndpoints.<init>(WebsocketClientEndpoints.java:32) ~[classes/:?]
	at com.draglet.service.websocket.WeSocketHandler.websocket(WeSocketHandler.java:24) ~[classes/:?]
	at com.draglet.service.communicator.BitfinexCommunicator.getOrderBook(BitfinexCommunicator.java:194) ~[classes/:?]
	... 8 more
Caused by: org.glassfish.tyrus.core.HandshakeException: Response code was not 101: 429.

**Comment by jnidzwetzki** [comment]
Hello achavan51,

Thank you very much for the report. The error message `Response code was not 101: 429` indicates, that the API-endpoint was overloaded (http status code 429 - Too Many Requests). 

The driver tries to reconnect automatically. Unfortunately, the client side cannot do any more in case of such a problem.

Best Regards
   Jan
