### ISSUE TITLE
Crypto currency codes more than 3 Characters

### ISSUE THREAD

**Issue by fotto412** [jnidzwetzki/bitfinex-v2-wss-api-java#271]
Hi,

When getting Margin trades positions, i get the below error for currencies with 4 digit codes:

02:22:19.502 [ tyrus-jdk-client-5] ERROR com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker - OnError called java.lang.IllegalArgumentException: Unable to find currency pair for: tLUNA:USD
	at com.github.jnidzwetzki.bitfinex.v2.entity.currency.BitfinexCurrencyPair.fromSymbolString(BitfinexCurrencyPair.java:259)
	at com.github.jnidzwetzki.bitfinex.v2.callback.channel.account.info.PositionHandler.jsonArrayToPosition(PositionHandler.java:93)
	at com.github.jnidzwetzki.bitfinex.v2.callback.channel.account.info.PositionHandler.handleChannelData(PositionHandler.java:70)
	at com.github.jnidzwetzki.bitfinex.v2.callback.channel.AccountInfoHandler.handleChannelData(AccountInfoHandler.java:129)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.handleChannelCallback(SimpleBitfinexApiBroker.java:599)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.websocketCallback(SimpleBitfinexApiBroker.java:532)
	at com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.onMessage(WebsocketClientEndpoint.java:117)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:552)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:65)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:651)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:855)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:196)
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:115)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:724)
	at org.glassfish.tyrus.container.jdk.client.ClientFilter.processRead(ClientFilter.java:204)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:111)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:113)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.handleRead(SslFilter.java:383)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.processRead(SslFilter.java:345)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:111)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:113)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:294)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:278)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by wgolyakov** [comment]
Maybe the list of pairs is not loaded.
`BitfinexCurrencyPair.registerDefaults();`
See [examples](https://github.com/jnidzwetzki/bitfinex-v2-wss-api-java/blob/master/EXAMPLES.md#available-currency-pairs).

**Comment by jnidzwetzki** [comment]
That was my thought, too. @fotto412 did you call the `BitfinexCurrencyPair.registerDefaults()` method?

Best regards
   Jan

**Comment by fotto412** [comment]
Ok guys that's my fault! I am using separate threads for each currency and
trying to call the static method  BitfinexCurrencyPair.registerDefaults()
in each separate thread. Moved  BitfinexCurrencyPair.registerDefaults()
call out of the threads to the main program everything is fine. Thanks a
lot for quick response. API is excellent by the way.

Best Regards,
Devrim

**Comment by mironbalcerzak** [comment]
> API is excellent by the way.

I know it is - thanks ;)

**Comment by jnidzwetzki** [comment]
Since the problem seems to be solved, I am closing this issue. If the error occurs again, feel free to open the issue again.

**Comment by fotto412** [comment]
Yes, it is working. Thank you for the great job.
