### ISSUE TITLE
Issue while parsing NULL in Order NotificationHandler

### ISSUE THREAD

**Issue by migunovAlex** [jnidzwetzki/bitfinex-v2-wss-api-java#28]
Hi Jan!

There is one more similar to submitted before issue :
```
Channel callback. Got message {}[0,"n",[1523930407542,"on-req",null,null,[null,null,1523930407442000,null,null,null,0.0001,null,"LIMIT",null,null,null,null,null,null,null,6800,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null],null,"ERROR","amount: invalid"]]
2018-04-17 10:00:07 - Got Error message: [0,"n",[1523930407542,"on-req",null,null,[null,null,1523930407442000,null,null,null,0.0001,null,"LIMIT",null,null,null,null,null,null,null,6800,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null],null,"ERROR","amount: invalid"]]
2018-04-17 10:00:07 - OnError called org.json.JSONException: JSONArray[3] not a string.
	at org.json.JSONArray.getString(JSONArray.java:450)
	at com.github.jnidzwetzki.bitfinex.v2.callback.api.NotificationHandler.handleErrorNotification(NotificationHandler.java:74)
```

**Comment by jnidzwetzki** [comment]
Hello migunovAlex,

Thank you very much for the report. I will fix this soon in the snapshot version.

Best Regards
   Jan
