### ISSUE TITLE
Compound order status parse exception

### ISSUE THREAD

**Issue by migunovAlex** [jnidzwetzki/bitfinex-v2-wss-api-java#30]
Hi Jan!

Got complicated order status response: INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 0.008049(-0.41291886).
Looks like it should be converted to PARTIALLY FILLED status, however there is a ExchangeOrderState.fromString method which tries to parse text to the status. I guess it should be parsed something like this:
```
public static ExchangeOrderState fromString(final String string) {
		
		Objects.requireNonNull(string);
		
		for (ExchangeOrderState state : ExchangeOrderState.values()) {
			if (string.startsWith(state.getBitfinexString())) {
				return state;
			}
		}

		if(string.contains("PARTIALLY FILLED")){
			return ExchangeOrderState.STATE_PARTIALLY_FILLED;
		}
		
		throw new IllegalArgumentException("Unable to find order type for: " + string);
	}
```

Response I got:
```
Got order callback [0,"oc",[11291120775,null,null,"tNEOBTC",1524661302976,1524661303001,0,-0.41291886,"MARKET",null,null,null,0,"INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 0.008049(-0.41291886)",null,null,0,0.008049,null,null,null,null,null,0,0,0,null,null,"",null,null,null]]
2018-04-25 16:01:43 - OnError called java.lang.IllegalArgumentException: Unable to find order type for: INSUFFICIENT BALANCE (G1) was: ACTIVE (note:POSCLOSE), PARTIALLY FILLED @ 0.008049(-0.41291886)
	at com.github.jnidzwetzki.bitfinex.v2.entity.ExchangeOrderState.fromString(ExchangeOrderState.java:51)
	at com.github.jnidzwetzki.bitfinex.v2.callback.api.OrderHandler.handleOrderCallback(OrderHandler.java:99)
	at com.github.jnidzwetzki.bitfinex.v2.callback.api.OrderHandler.handleChannelData(OrderHandler.java:55)
```

**Comment by jnidzwetzki** [comment]
Hello Alex,

Thanks for the report. This will be fixed in the next snapshot version.

Best Regards
    Jan
