### ISSUE TITLE
SimpleBitfinexApiBroker - OnError called java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "action" is null

### ISSUE THREAD

**Issue by GeekHare** [jnidzwetzki/bitfinex-v2-wss-api-java#317]
`
16:03:59.942 [33] ERROR c.g.j.b.v.SimpleBitfinexApiBroker - OnError called java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "action" is null
	at com.github.jnidzwetzki.bitfinex.v2.callback.channel.ExecutedTradeHandler.handleChannelData(ExecutedTradeHandler.java:54)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.handleChannelCallback(SimpleBitfinexApiBroker.java:608)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.websocketCallback(SimpleBitfinexApiBroker.java:536)
	at com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.onMessage(WebsocketClientEndpoint.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:866)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:196)
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:116)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
	at org.glassfish.tyrus.container.jdk.client.ClientFilter.processRead(ClientFilter.java:204)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:111)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:113)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.handleRead(SslFilter.java:402)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.processRead(SslFilter.java:365)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:111)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:113)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:295)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:279)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by GeekHare** [comment]
Hey @jnidzwetzki, I've fixed it in this PR https://github.com/jnidzwetzki/bitfinex-v2-wss-api-java/pull/318
