### ISSUE TITLE
Issue with currencies symbol more than 3 characters(ver:0.7.7

### ISSUE THREAD

**Issue by fotto412** [jnidzwetzki/bitfinex-v2-wss-api-java#345]
16:44:20.438 [ tyrus-jdk-client-5] ERROR com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker - OnError called java.lang.IllegalArgumentException: Unable to parse: trade:1h:tAVAX:USD
	at com.github.jnidzwetzki.bitfinex.v2.symbol.BitfinexCandlestickSymbol.fromBitfinexString(BitfinexCandlestickSymbol.java:70)
	at com.github.jnidzwetzki.bitfinex.v2.callback.command.SubscribedCallback.handleCandlesCallback(SubscribedCallback.java:89)
	at com.github.jnidzwetzki.bitfinex.v2.callback.command.SubscribedCallback.handleChannelData(SubscribedCallback.java:56)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.handleCommandCallback(SimpleBitfinexApiBroker.java:552)
	at com.github.jnidzwetzki.bitfinex.v2.SimpleBitfinexApiBroker.websocketCallback(SimpleBitfinexApiBroker.java:530)
	at com.github.jnidzwetzki.bitfinex.v2.WebsocketClientEndpoint.onMessage(WebsocketClientEndpoint.java:117)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:552)
	at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:65)
	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:651)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:855)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:196)
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:115)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:724)
	at org.glassfish.tyrus.container.jdk.client.ClientFilter.processRead(ClientFilter.java:204)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:111)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:113)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.handleRead(SslFilter.java:383)
	at org.glassfish.tyrus.container.jdk.client.SslFilter.processRead(SslFilter.java:345)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:111)
	at org.glassfish.tyrus.container.jdk.client.Filter.onRead(Filter.java:113)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:294)
	at org.glassfish.tyrus.container.jdk.client.TransportFilter$4.completed(TransportFilter.java:278)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by wgolyakov** [comment]
Fixed in version 0.7.8 (#209).

**Comment by fotto412** [comment]
Great! Tested and seems to be working. Awsome team!
